# Generated by Django 3.1.5 on 2021-07-27 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('book_date', models.DateField()),
                ('age', models.IntegerField()),
                ('book_detail', models.CharField(max_length=255)),
                ('bread', models.IntegerField(default=0)),
                ('bcomment', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('introduction', models.CharField(default='', max_length=255)),
                ('sector', models.CharField(default='', max_length=255)),
                ('company_categary', models.CharField(default='', max_length=255)),
                ('point', models.JSONField(blank=True, null=True)),
                ('auth', models.CharField(default='', max_length=255)),
                ('zhuce_time', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('categary', models.CharField(default='', max_length=255)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('pgps', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MapAchivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ach_name', models.CharField(max_length=255)),
                ('ach_people', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_unit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_keywords', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_clc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_sc', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_introduction', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_categary', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_inyear', models.CharField(blank=True, max_length=255, null=True)),
                ('ach_researchtime', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_evaluform', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_level', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_prisectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_auxsectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ach_fourthsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('point', models.JSONField(blank=True, null=True)),
                ('ach_radius', models.IntegerField()),
                ('ach_remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_introduction', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_prisector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_auxsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_fourthsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_categary', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('point', models.JSONField(blank=True, null=True)),
                ('company_auth', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_time', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_item', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('company_year', models.CharField(blank=True, max_length=255, null=True)),
                ('company_xzqy', models.CharField(blank=True, max_length=255, null=True)),
                ('company_radius', models.IntegerField()),
                ('company_remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=255)),
                ('instrument_address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('point', models.JSONField(blank=True, null=True)),
                ('instrument_category', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_pay', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_prisectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_auxsectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_fourthsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_contact', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_reuse', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instrument_radius', models.IntegerField()),
                ('instrument_remark', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapPrograme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_people', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_position', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_unit', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_corcomp', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_technology', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_introduction', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_compeople', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('pro_year', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_prisectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_auxsectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('pro_fourthsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('point', models.JSONField(blank=True, null=True)),
                ('pro_remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_title', models.CharField(max_length=255)),
                ('teacher_position', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('teacher_research', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('teacher_college', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('point', models.JSONField(blank=True, null=True)),
                ('teacher_program', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('teacher_prisectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('teacher_auxsectorsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('teacher_fourthsector', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('teacher_radius', models.IntegerField()),
                ('teacher_remark', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
                ('book_people', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='loverswhite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('isDelete', models.BooleanField(default=False)),
                ('book_lwhite', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.bookinfo')),
            ],
        ),
    ]
